name: Build Master

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build-plugin:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v5
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build with Gradle
        run: ./gradlew build -x test
      - name: Run Unit tests
        run: ./gradlew test --tests 'com.plugin.samusprogressbar.settings*'
      - name: Cleanup Gradle Cache
        # Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
        # Restoring these files from a GitHub Actions cache might cause problems for future builds.
        run: |
          rm --force ~/.gradle/caches/modules-2/modules-2.lock
          rm --force ~/.gradle/caches/modules-2/gc.properties

  integration-test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: Clean
        run: ./gradlew clean
#      - name: Run Idea
#        run: start gradlew.bat runIdeForUiTests
#      - name: Wait for Idea started
#        uses: jtalk/url-health-check-action@v4
#        with:
#          url: http://127.0.0.1:8082
#          max-attempts: 15
#          retry-delay: 30s
      - name: Run Integration tests
        run: ./gradlew test --tests '*IntegrationTest'
